name: MinecraftCheats
main: com.github.risen619.MinecraftCheats.Main
version: 1.0.0
commands:
    heal:
        description: Adds air and heals you or specified player.
        usage: /<command> <player>
        aliases: [h]
    feed:
        description: Feeds you or specified player.
        usage: /<command> <player>
    speed:
        description: Speeds up you or specified player.
        usage: /<command> <duration> <amplifier> <player>
    vanish:
        description: Makes you or specified player invisible/visible.
        usage: /<command> <player> <duration>
        aliases: [v]
    burn:
        description: Sets specified player burning.
        usage: /<command> <player> <duration>
    hat:
        description: Puts block you hold on your head.
        usage: /<command> <player>
    potato:
        description: Fills specified player's inventory with potato, hard will replace his items.
        usage: /<command> <player> [hard]
    trap:
        description: Traps specified player's
        usage: /<command> <player> <block>
    repair:
        description: Repairs the item you hold in main hand.
        usage: /<command>
        aliases: [rep]
    lightning:
        description: Lightning strikes specified player.
        usage: /<command> <player>
        aliases: [thor, zeus, strike]
    explosion:
        description: Explodes specified player.
        usage: /<command> <player>
        aliases: [explode, boom]
    slow:
        description: Slows you or specified player.
        usage: /<command> <player> <duration> <amplifier>
    launch:
        description: Launches specified player in air.
        usage: /<command> <player> <force>
    fly:
        description: Toggle fly mode.
        usage: /<command> <player>