name: MinecraftCheats
main: com.github.risen619.MinecraftCheats.Main
version: 1.0.0
commands:
    heal:
        description: Adds air and heals you or the specified player.
        usage: /<command> [player]
        aliases: [h]
    feed:
        description: Feeds you or the specified player.
        usage: /<command> [player]
    burn:
        description: Sets you or the specified player burning.
        usage: /<command> [player] [duration/%d/pos]
    hat:
        description: Puts the block you hold on your head.
        usage: /<command> [player]
    potato:
        description: Fills the specified player's inventory with potato, hard will replace his items.
        usage: /<command> [player] [hard/%s/^hard$]
    trap:
        description: Traps you or the specified player's
        usage: /<command> [player] [block]
    repair:
        description: Repairs the item you hold in the main hand.
        usage: /<command>
        aliases: [rep]
    lightning:
        description: Lightning strikes you or the specified player.
        usage: /<command> [player]
        aliases: [thor, zeus, strike]
    explosion:
        description: Explodes you or the specified player.
        usage: /<command> [player]
        aliases: [explode, boom]
    launch:
        description: Launches you or the specified player in air.
        usage: /<command> [player] [force/%d/pos]
    fly:
        description: Toggle fly mode.
        usage: /<command> [player]
    dazzle:
        description: Makes you or the specified player blind.
        usage: /<command> [player/%s] [amplifier/%d/pos] [duration/%d/pos]
        aliases: [blind]
    poison:
        description: Poisons you or the specified player.
        usage: /<command> [player/%s] [amplifier/%d/pos] [duration/%d/pos]
    strength:
        description: Raises strength of the specified player.
        usage: /<command> [player/%s] [amplifier/%d/pos] [duration/%d/pos]
        aliases: [power]
    slow:
        description: Slows you or the specified player.
        usage: /<command> [player/%s] [amplifier/%d/pos] [duration/%d/pos]
    speed:
        description: Speeds up you or the specified player.
        usage: /<command> [player/%s] [amplifier/%d/pos] [duration/%d/pos]
    jump:
        description: Increases jumping ability of the specified player.
        usage: /<command> [player/%s] [amplifier/%d/pos] [duration/%d/pos]
    vanish:
        description: Makes you or the specified player invisible/visible.
        usage: /<command> [player] [duration/%d/pos]
        aliases: [v]
    luck:
        description: Just luck.
        usage: /<command> [player] [amplifier/%d/pos] [duration/%d/pos]
    unluck:
        description: Just unluck.
        usage: /<command> [player] [amplifier/%d/pos] [duration/%d/pos]
    resist:
        description: Add some damage resistance to the specified player.
        usage: /<command> [player] [amplifier/%d/pos] [duration/%d/pos]
        aliases: [armor]
    weaken:
        description: Weakens you or the specified player.
        usage: /<command> [player] [amplifier/%d/pos] [duration/%d/pos]
        aliases: [weak]